。。。

diff --git a/.github/workflows/build_release.yml b/.github/workflows/build_release.yml
--- a/.github/workflows/build_release.yml
+++ b/.github/workflows/build_release.yml
@@ -83,16 +83,16 @@ jobs:
           git config user.name "The OpenList Bot"
           git config user.email "bot@openlist.team"
 
-      - name: Update package.json and commit
-        if: github.event_name == 'workflow_dispatch'
-        run: |
-          jq --arg version "${{ steps.semver.outputs.version }}" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json
-          git add package.json
-          git commit -S -m "chore: release v${{ steps.semver.outputs.version }}" --no-verify
-          git push
+      # - name: Update package.json and commit
+      #   if: github.event_name == 'workflow_dispatch'
+      #   run: |
+      #     jq --arg version "${{ steps.semver.outputs.version }}" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json
+      #     git add package.json
+      #     git commit -S -m "chore: release v${{ steps.semver.outputs.version }}" --no-verify
+      #     git push
 
-          # For local build, needn't push, the tag will be created by `gh release create`
-          git tag -s "v${{ steps.semver.outputs.version }}" -m "Release v${{ steps.semver.outputs.version }}"
+      #     # For local build, needn't push, the tag will be created by `gh release create`
+      #     git tag -s "v${{ steps.semver.outputs.version }}" -m "Release v${{ steps.semver.outputs.version }}"
 
       - name: Get current tag
         id: get_current_tag
@@ -180,30 +180,30 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Publish npm
-        run: |
-          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
-          # Delete the generated dist tarball
-          rm -f dist/openlist-frontend-dist-v*.tar.gz
-          rm -f lite/dist/openlist-frontend-dist-lite-v*.tar.gz
-          # Copy the lite version
-          mkdir dist/lite
-          cp -r lite/dist/. dist/lite/
+      # - name: Publish npm
+      #   run: |
+      #     echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
+      #     # Delete the generated dist tarball
+      #     rm -f dist/openlist-frontend-dist-v*.tar.gz
+      #     rm -f lite/dist/openlist-frontend-dist-lite-v*.tar.gz
+      #     # Copy the lite version
+      #     mkdir dist/lite
+      #     cp -r lite/dist/. dist/lite/
 
-          if ! jq -e '.name and .version' package.json > /dev/null; then
-            echo "Error: Invalid package.json"
-            exit 1
-          fi
+      #     if ! jq -e '.name and .version' package.json > /dev/null; then
+      #       echo "Error: Invalid package.json"
+      #       exit 1
+      #     fi
 
-          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
-            echo "NPM_TOKEN not set, performing dry run"
-            pnpm publish --dry-run --no-git-checks --access public
-          else
-            echo "Publishing to npm..."
-            pnpm publish --no-git-checks --access public
-          fi
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+      #     if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
+      #       echo "NPM_TOKEN not set, performing dry run"
+      #       pnpm publish --dry-run --no-git-checks --access public
+      #     else
+      #       echo "Publishing to npm..."
+      #       pnpm publish --no-git-checks --access public
+      #     fi
+      #   env:
+      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
 permissions:
   contents: write
